[package]
name = "cargo-vet"
version = "0.1.0"
edition = "2021"
authors = ["Bobby Holley <bobbyholley@gmail.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/bholley/cargo-vet"
homepage = "https://bholley.net/cargo-vet"
description = "Supply-chain security for Rust"
exclude = [
  "book/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_metadata = "0.14.2"
clap = "3.1.11"
clap-cargo = "0.8.0"
eyre = "0.6.8"
home = "0.5.3"
linked-hash-map = { version = "0.5.4", features = ["serde_impl"] }
log = "0.4.16"
reqwest = { version = "0.11.10", features = ["blocking"] }
serde = "1.0.136"
serde_json = "1.0.79"
simplelog = "0.12.0"
tempfile = "3.3.0"
toml = "0.5.8"

[dev-dependencies]
insta = "1.13.0" 

[package.metadata.vet]
audits = []

